apiVersion: apps/v1
kind: Deployment
metadata:
  name: rizurin-app
  namespace: rizurin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rizurin-app
  template:
    metadata:
      labels:
        app: rizurin-app
    spec:
      containers:
        - name: rizurin-app
          image: 192.168.8.60:8085/rizurin/rizurin-app:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: harbor-secret
