apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rizurin-https
  namespace: rizurin
spec:
  entryPoints:
    - websecure          # HTTPS entrypoint (port 8443)
  routes:
    - match: Host(`rizurin.my.id`)
      kind: Rule
      services:
        - name: rizurin-app
          port: 80
  tls:
    certResolver: cloudflare
