apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rizurin-http
  namespace: rizurin
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`rizurin.my.id`)
      kind: Rule
      middlewares:
        - name: https-redirect
      services:
        - name: noop@internal