
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rizurin-ingress
  namespace: rizurin
spec:
  rules:
    - host: rizurin.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rizurin-app
                port:
                  number: 80